#!/bin/bash
START=$(date -u +%s.%N)

BLINK='\033[5m'
IRED='\033[0;91m'
RED='\033[0;31m'
BIYELLOW='\033[5;93m'
IYELLOW='\033[0;93m'
YELLOW='\033[0;33m'
NoColor='\033[0m' # No Color

"$@"

STOP=$(date -u +%s.%N)
echo -e -n "Run time: ${IYELLOW}"
#date -u -d "0 $STOP sec - $START sec" +"%H:%M:%S.%N (HH:MM:SS)"
#date -u -d "0 $STOP sec - $START sec" +"%H:%M:%S.%N" | xargs echo -n
date -u -d "0 $STOP sec - $START sec" +"%H:%M:%S.%N" | xargs echo -n
echo -e "${NoColor} (HH:MM:SS)"
